// AUTO-GENERATED by scripts/decode_section_table.py-based generator — do not hand-edit.
// Rebuilds the Ghidra memory map for default.xbe (original Xbox, x86) from the
// CORRECTED 32-entry XBE section table (table anchor 0x370, canonical XBE_SECTION
// struct layout — see Xbox Ghoulies Linux Port.md for why opencode's 0x37C anchor
// was wrong). Must run as a -postScript immediately after a raw BinaryLoader
// import of default.xbe at scratch base 0x90000000, block name FLATFILE,
// language x86:LE:32:default, with -noanalysis.
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.mem.Memory;
import ghidra.program.model.mem.MemoryBlock;
import ghidra.program.model.listing.Function;
import java.util.ArrayList;
import java.util.List;

public class RemapGhoulies extends GhidraScript {

    static final long XBE_BASE = 0x10000L;
    static final long FLAT_BASE = 0x90000000L;
    static final long ENTRY_VA = 0x14FAE9L;   // retail-XOR decode, verified inside .text
    static final long KTHUNK_VA = 0x202EA0L; // retail-XOR decode, verified at .rdata start

    static class Sect {
        String name; long rva, vsize, raw, rawsz; String perm;
        Sect(String n, long rva, long vsize, long raw, long rawsz, String perm) {
            this.name = n; this.rva = rva; this.vsize = vsize;
            this.raw = raw; this.rawsz = rawsz; this.perm = perm;
        }
    }

    static final Sect[] SECTIONS = {
        new Sect(".text", 0x11000L, 0x160020L, 0x1000L, 0x160020L, "RX"),
        new Sect("D3D", 0x171020L, 0x135D8L, 0x162000L, 0xFD2CL, "RX"),
        new Sect("D3DX", 0x184600L, 0xE40L, 0x172000L, 0xE3CL, "RX"),
        new Sect("XGRPH", 0x185440L, 0x20598L, 0x173000L, 0x1F91CL, "RX"),
        new Sect("BINK", 0x1A59E0L, 0xD3ACL, 0x193000L, 0xD3ACL, "RX"),
        new Sect("BINK32", 0x1B2DA0L, 0x1175L, 0x1A1000L, 0x1174L, "RX"),
        new Sect("BINK32A", 0x1B3F20L, 0x1489L, 0x1A3000L, 0x1488L, "RX"),
        new Sect("BINK16", 0x1B53C0L, 0x123CL, 0x1A5000L, 0x123CL, "RX"),
        new Sect("BINK4444", 0x1B6600L, 0x14C0L, 0x1A7000L, 0x14C0L, "RX"),
        new Sect("BINK5551", 0x1B7AC0L, 0x10B4L, 0x1A9000L, 0x10B4L, "RX"),
        new Sect("BINKYUY2_0", 0x1B8B80L, 0xCACL, 0x1AB000L, 0xCACL, "RX"),
        new Sect("BINKYUY2_1", 0x1B9840L, 0x9CL, 0x1AC000L, 0x9CL, "RX"),
        new Sect("BINKYUY2_2", 0x1B98E0L, 0xB8L, 0x1AD000L, 0xB8L, "RX"),
        new Sect("BINKYUY2_3", 0x1B99A0L, 0x88L, 0x1AE000L, 0x88L, "RX"),
        new Sect("BINK16MX", 0x1B9A40L, 0x130L, 0x1AF000L, 0x130L, "RX"),
        new Sect("BINK16X2", 0x1B9B80L, 0x558L, 0x1B0000L, 0x558L, "RX"),
        new Sect("BINK16M", 0x1BA0E0L, 0x1F8L, 0x1B1000L, 0x1F8L, "RX"),
        new Sect("BINK32MX", 0x1BA2E0L, 0x1BCL, 0x1B2000L, 0x1BCL, "RX"),
        new Sect("BINK32X2", 0x1BA4A0L, 0x58CL, 0x1B3000L, 0x58CL, "RX"),
        new Sect("BINK32M", 0x1BAA40L, 0x14CL, 0x1B4000L, 0x14CL, "RX"),
        new Sect("XACTENG", 0x1BABA0L, 0xAC30L, 0x1B5000L, 0xABDCL, "RX"),
        new Sect("DSOUND", 0x1C57E0L, 0x1E534L, 0x1C0000L, 0x1E2CCL, "RX"),
        new Sect("WMADEC", 0x1E3D20L, 0x1907CL, 0x1DF000L, 0x1907CL, "RX"),
        new Sect("XPP", 0x1FCDA0L, 0x60FCL, 0x1F9000L, 0x60FCL, "RX"),
        new Sect(".rdata", 0x202EA0L, 0x129958L, 0x200000L, 0x129948L, "R"),
        new Sect(".data", 0x32C800L, 0x222FC0L, 0x32A000L, 0x107A14L, "RW"),
        new Sect("BINKDATA", 0x54F7C0L, 0xF5E0L, 0x432000L, 0xF5D4L, "RW"),
        new Sect("DOLBY", 0x55EDA0L, 0x7180L, 0x442000L, 0x716CL, "R"),
        new Sect("_DLR__DLR_XTIMAGE", 0x565F20L, 0x4800L, 0x44D000L, 0x4800L, "R"),
        new Sect("_DLR__DLR_XSIMAGE", 0x56A720L, 0x4800L, 0x452000L, 0x4800L, "R"),
        new Sect("dirtydisk_bitmap", 0x56EF20L, 0x28BEL, 0x44A000L, 0x28BEL, "R"),
        new Sect(".XTLID", 0x5717E0L, 0x7A0L, 0x457000L, 0x7A0L, "R"),
    };

    @Override
    public void run() throws Exception {
        Memory mem = currentProgram.getMemory();
        MemoryBlock flat = mem.getBlock("FLATFILE");
        if (flat == null) {
            println("ERROR: FLATFILE scratch block not found - check -loader-blockName");
            return;
        }
        Address flatBase = flat.getStart();
        println("flat scratch block at " + flatBase);

        // The XBE header itself (file 0x0..0xF60, "size of headers") lives at VA
        // 0x10000..0x10F60 - BELOW .text's start (0x11000) and not covered by any
        // of the 32 named sections. entry() reads header fields directly
        // (_DAT_00010108 etc.), so without this block those reads hit unmapped
        // memory - fatal for a real loader, and shows as unbacked _DAT_ globals here.
        {
            long hdrLen = 0xF60L;
            Address hdrDest = toAddr(XBE_BASE);
            if (mem.getBlock(hdrDest) == null) {
                MemoryBlock hdrBlock = mem.createInitializedBlock("xbe_header", hdrDest, hdrLen,
                        (byte) 0, monitor, false);
                byte[] buf = new byte[(int) hdrLen];
                int got = mem.getBytes(flatBase, buf);
                mem.setBytes(hdrDest, buf, 0, got);
                hdrBlock.setRead(true);
                hdrBlock.setWrite(false);
                hdrBlock.setExecute(false);
                println(String.format("mapped %-18s %s len=0x%x perm=R", "xbe_header", hdrDest, hdrLen));
            }
        }

        List<MemoryBlock> created = new ArrayList<>();
        for (Sect s : SECTIONS) {
            Address dest = toAddr(s.rva);
            long blockLen = Math.max(s.vsize, s.rawsz);
            if (blockLen <= 0) {
                println("skip zero-length section " + s.name);
                continue;
            }
            MemoryBlock existing = mem.getBlock(dest);
            if (existing != null) {
                println("WARNING: " + s.name + " at " + dest + " overlaps existing block "
                        + existing.getName() + " - skipping");
                continue;
            }
            MemoryBlock nb = mem.createInitializedBlock(s.name, dest, blockLen, (byte) 0,
                    monitor, false);
            long copyLen = Math.min(s.rawsz, blockLen);
            if (copyLen > 0) {
                byte[] buf = new byte[(int) copyLen];
                int got = mem.getBytes(flatBase.add(s.raw), buf);
                mem.setBytes(dest, buf, 0, got);
            }
            nb.setRead(true);
            nb.setWrite(s.perm.contains("W"));
            nb.setExecute(s.perm.contains("X"));
            created.add(nb);
            println(String.format("mapped %-18s %s len=0x%x perm=%s", s.name, dest,
                    blockLen, s.perm));
        }

        // drop the flat scratch copy now that every section has its own block
        mem.removeBlock(flat, monitor);
        println("removed FLATFILE scratch block (" + created.size() + " real sections mapped)");

        Address entryAddr = toAddr(ENTRY_VA);
        try {
            Function f = createFunction(entryAddr, "entry");
            if (f != null) {
                println("seeded entry point function at " + entryAddr);
            } else {
                println("createFunction returned null at " + entryAddr + " - will rely on auto-analysis");
            }
        }
        catch (Exception e) {
            println("could not create entry function: " + e.getMessage());
        }

        println("kernel thunk table (not yet walked) expected at " + toAddr(KTHUNK_VA));

        println("running full auto-analysis now that the memory map is correct...");
        analyzeAll(currentProgram);
        println("auto-analysis complete.");
    }
}
