// AUTO-GENERATED from scripts/xboxkrnl_ordinals.tsv (sourced from XboxDev/nxdk's
// xboxkrnl.exe.def) — do not hand-edit the map, regenerate instead.
// Walks the Kernel Image Thunk Table (verified at VA 0x202EA0, start of .rdata,
// via retail-XOR decode cross-checked in Xbox Ghoulies Linux Port.md) and labels
// each ordinal-encoded thunk slot with its real xboxkrnl.exe function name.
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;
import ghidra.program.model.symbol.ReferenceManager;
import ghidra.program.model.symbol.SourceType;
import ghidra.program.model.listing.Function;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WalkKernelThunk extends GhidraScript {

    static final long KTHUNK_VA = 0x202EA0L;
    static final int MAX_ENTRIES = 400; // 378 known ordinals + margin; loop stops at 0 anyway

    static Map<Integer, String> ordinalNames() {
        Map<Integer, String> map = new HashMap<>();
        map.put(1, "AvGetSavedDataAddress");
        map.put(2, "AvSendTVEncoderOption");
        map.put(3, "AvSetDisplayMode");
        map.put(4, "AvSetSavedDataAddress");
        map.put(5, "DbgBreakPoint");
        map.put(6, "DbgBreakPointWithStatus");
        map.put(7, "DbgLoadImageSymbols");
        map.put(8, "DbgPrint");
        map.put(9, "HalReadSMCTrayState");
        map.put(10, "DbgPrompt");
        map.put(11, "DbgUnLoadImageSymbols");
        map.put(12, "ExAcquireReadWriteLockExclusive");
        map.put(13, "ExAcquireReadWriteLockShared");
        map.put(14, "ExAllocatePool");
        map.put(15, "ExAllocatePoolWithTag");
        map.put(16, "ExEventObjectType");
        map.put(17, "ExFreePool");
        map.put(18, "ExInitializeReadWriteLock");
        map.put(19, "ExInterlockedAddLargeInteger");
        map.put(20, "ExInterlockedAddLargeStatistic");
        map.put(21, "ExInterlockedCompareExchange64");
        map.put(22, "ExMutantObjectType");
        map.put(23, "ExQueryPoolBlockSize");
        map.put(24, "ExQueryNonVolatileSetting");
        map.put(25, "ExReadWriteRefurbInfo");
        map.put(26, "ExRaiseException");
        map.put(27, "ExRaiseStatus");
        map.put(28, "ExReleaseReadWriteLock");
        map.put(29, "ExSaveNonVolatileSetting");
        map.put(30, "ExSemaphoreObjectType");
        map.put(31, "ExTimerObjectType");
        map.put(32, "ExfInterlockedInsertHeadList");
        map.put(33, "ExfInterlockedInsertTailList");
        map.put(34, "ExfInterlockedRemoveHeadList");
        map.put(35, "FscGetCacheSize");
        map.put(36, "FscInvalidateIdleBlocks");
        map.put(37, "FscSetCacheSize");
        map.put(38, "HalClearSoftwareInterrupt");
        map.put(39, "HalDisableSystemInterrupt");
        map.put(40, "HalDiskCachePartitionCount");
        map.put(41, "HalDiskModelNumber");
        map.put(42, "HalDiskSerialNumber");
        map.put(43, "HalEnableSystemInterrupt");
        map.put(44, "HalGetInterruptVector");
        map.put(45, "HalReadSMBusValue");
        map.put(46, "HalReadWritePCISpace");
        map.put(47, "HalRegisterShutdownNotification");
        map.put(48, "HalRequestSoftwareInterrupt");
        map.put(49, "HalReturnToFirmware");
        map.put(50, "HalWriteSMBusValue");
        map.put(51, "InterlockedCompareExchange");
        map.put(52, "InterlockedDecrement");
        map.put(53, "InterlockedIncrement");
        map.put(54, "InterlockedExchange");
        map.put(55, "InterlockedExchangeAdd");
        map.put(56, "InterlockedFlushSList");
        map.put(57, "InterlockedPopEntrySList");
        map.put(58, "InterlockedPushEntrySList");
        map.put(59, "IoAllocateIrp");
        map.put(60, "IoBuildAsynchronousFsdRequest");
        map.put(61, "IoBuildDeviceIoControlRequest");
        map.put(62, "IoBuildSynchronousFsdRequest");
        map.put(63, "IoCheckShareAccess");
        map.put(64, "IoCompletionObjectType");
        map.put(65, "IoCreateDevice");
        map.put(66, "IoCreateFile");
        map.put(67, "IoCreateSymbolicLink");
        map.put(68, "IoDeleteDevice");
        map.put(69, "IoDeleteSymbolicLink");
        map.put(70, "IoDeviceObjectType");
        map.put(71, "IoFileObjectType");
        map.put(72, "IoFreeIrp");
        map.put(73, "IoInitializeIrp");
        map.put(74, "IoInvalidDeviceRequest");
        map.put(75, "IoQueryFileInformation");
        map.put(76, "IoQueryVolumeInformation");
        map.put(77, "IoQueueThreadIrp");
        map.put(78, "IoRemoveShareAccess");
        map.put(79, "IoSetIoCompletion");
        map.put(80, "IoSetShareAccess");
        map.put(81, "IoStartNextPacket");
        map.put(82, "IoStartNextPacketByKey");
        map.put(83, "IoStartPacket");
        map.put(84, "IoSynchronousDeviceIoControlRequest");
        map.put(85, "IoSynchronousFsdRequest");
        map.put(86, "IofCallDriver");
        map.put(87, "IofCompleteRequest");
        map.put(88, "KdDebuggerEnabled");
        map.put(89, "KdDebuggerNotPresent");
        map.put(90, "IoDismountVolume");
        map.put(91, "IoDismountVolumeByName");
        map.put(92, "KeAlertResumeThread");
        map.put(93, "KeAlertThread");
        map.put(94, "KeBoostPriorityThread");
        map.put(95, "KeBugCheck");
        map.put(96, "KeBugCheckEx");
        map.put(97, "KeCancelTimer");
        map.put(98, "KeConnectInterrupt");
        map.put(99, "KeDelayExecutionThread");
        map.put(100, "KeDisconnectInterrupt");
        map.put(101, "KeEnterCriticalRegion");
        map.put(102, "MmGlobalData");
        map.put(103, "KeGetCurrentIrql");
        map.put(104, "KeGetCurrentThread");
        map.put(105, "KeInitializeApc");
        map.put(106, "KeInitializeDeviceQueue");
        map.put(107, "KeInitializeDpc");
        map.put(108, "KeInitializeEvent");
        map.put(109, "KeInitializeInterrupt");
        map.put(110, "KeInitializeMutant");
        map.put(111, "KeInitializeQueue");
        map.put(112, "KeInitializeSemaphore");
        map.put(113, "KeInitializeTimerEx");
        map.put(114, "KeInsertByKeyDeviceQueue");
        map.put(115, "KeInsertDeviceQueue");
        map.put(116, "KeInsertHeadQueue");
        map.put(117, "KeInsertQueue");
        map.put(118, "KeInsertQueueApc");
        map.put(119, "KeInsertQueueDpc");
        map.put(120, "KeInterruptTime");
        map.put(121, "KeIsExecutingDpc");
        map.put(122, "KeLeaveCriticalRegion");
        map.put(123, "KePulseEvent");
        map.put(124, "KeQueryBasePriorityThread");
        map.put(125, "KeQueryInterruptTime");
        map.put(126, "KeQueryPerformanceCounter");
        map.put(127, "KeQueryPerformanceFrequency");
        map.put(128, "KeQuerySystemTime");
        map.put(129, "KeRaiseIrqlToDpcLevel");
        map.put(130, "KeRaiseIrqlToSynchLevel");
        map.put(131, "KeReleaseMutant");
        map.put(132, "KeReleaseSemaphore");
        map.put(133, "KeRemoveByKeyDeviceQueue");
        map.put(134, "KeRemoveDeviceQueue");
        map.put(135, "KeRemoveEntryDeviceQueue");
        map.put(136, "KeRemoveQueue");
        map.put(137, "KeRemoveQueueDpc");
        map.put(138, "KeResetEvent");
        map.put(139, "KeRestoreFloatingPointState");
        map.put(140, "KeResumeThread");
        map.put(141, "KeRundownQueue");
        map.put(142, "KeSaveFloatingPointState");
        map.put(143, "KeSetBasePriorityThread");
        map.put(144, "KeSetDisableBoostThread");
        map.put(145, "KeSetEvent");
        map.put(146, "KeSetEventBoostPriority");
        map.put(147, "KeSetPriorityProcess");
        map.put(148, "KeSetPriorityThread");
        map.put(149, "KeSetTimer");
        map.put(150, "KeSetTimerEx");
        map.put(151, "KeStallExecutionProcessor");
        map.put(152, "KeSuspendThread");
        map.put(153, "KeSynchronizeExecution");
        map.put(154, "KeSystemTime");
        map.put(155, "KeTestAlertThread");
        map.put(156, "KeTickCount");
        map.put(157, "KeTimeIncrement");
        map.put(158, "KeWaitForMultipleObjects");
        map.put(159, "KeWaitForSingleObject");
        map.put(160, "KfRaiseIrql");
        map.put(161, "KfLowerIrql");
        map.put(162, "KiBugCheckData");
        map.put(163, "KiUnlockDispatcherDatabase");
        map.put(164, "LaunchDataPage");
        map.put(165, "MmAllocateContiguousMemory");
        map.put(166, "MmAllocateContiguousMemoryEx");
        map.put(167, "MmAllocateSystemMemory");
        map.put(168, "MmClaimGpuInstanceMemory");
        map.put(169, "MmCreateKernelStack");
        map.put(170, "MmDeleteKernelStack");
        map.put(171, "MmFreeContiguousMemory");
        map.put(172, "MmFreeSystemMemory");
        map.put(173, "MmGetPhysicalAddress");
        map.put(174, "MmIsAddressValid");
        map.put(175, "MmLockUnlockBufferPages");
        map.put(176, "MmLockUnlockPhysicalPage");
        map.put(177, "MmMapIoSpace");
        map.put(178, "MmPersistContiguousMemory");
        map.put(179, "MmQueryAddressProtect");
        map.put(180, "MmQueryAllocationSize");
        map.put(181, "MmQueryStatistics");
        map.put(182, "MmSetAddressProtect");
        map.put(183, "MmUnmapIoSpace");
        map.put(184, "NtAllocateVirtualMemory");
        map.put(185, "NtCancelTimer");
        map.put(186, "NtClearEvent");
        map.put(187, "NtClose");
        map.put(188, "NtCreateDirectoryObject");
        map.put(189, "NtCreateEvent");
        map.put(190, "NtCreateFile");
        map.put(191, "NtCreateIoCompletion");
        map.put(192, "NtCreateMutant");
        map.put(193, "NtCreateSemaphore");
        map.put(194, "NtCreateTimer");
        map.put(195, "NtDeleteFile");
        map.put(196, "NtDeviceIoControlFile");
        map.put(197, "NtDuplicateObject");
        map.put(198, "NtFlushBuffersFile");
        map.put(199, "NtFreeVirtualMemory");
        map.put(200, "NtFsControlFile");
        map.put(201, "NtOpenDirectoryObject");
        map.put(202, "NtOpenFile");
        map.put(203, "NtOpenSymbolicLinkObject");
        map.put(204, "NtProtectVirtualMemory");
        map.put(205, "NtPulseEvent");
        map.put(206, "NtQueueApcThread");
        map.put(207, "NtQueryDirectoryFile");
        map.put(208, "NtQueryDirectoryObject");
        map.put(209, "NtQueryEvent");
        map.put(210, "NtQueryFullAttributesFile");
        map.put(211, "NtQueryInformationFile");
        map.put(212, "NtQueryIoCompletion");
        map.put(213, "NtQueryMutant");
        map.put(214, "NtQuerySemaphore");
        map.put(215, "NtQuerySymbolicLinkObject");
        map.put(216, "NtQueryTimer");
        map.put(217, "NtQueryVirtualMemory");
        map.put(218, "NtQueryVolumeInformationFile");
        map.put(219, "NtReadFile");
        map.put(220, "NtReadFileScatter");
        map.put(221, "NtReleaseMutant");
        map.put(222, "NtReleaseSemaphore");
        map.put(223, "NtRemoveIoCompletion");
        map.put(224, "NtResumeThread");
        map.put(225, "NtSetEvent");
        map.put(226, "NtSetInformationFile");
        map.put(227, "NtSetIoCompletion");
        map.put(228, "NtSetSystemTime");
        map.put(229, "NtSetTimerEx");
        map.put(230, "NtSignalAndWaitForSingleObjectEx");
        map.put(231, "NtSuspendThread");
        map.put(232, "NtUserIoApcDispatcher");
        map.put(233, "NtWaitForSingleObject");
        map.put(234, "NtWaitForSingleObjectEx");
        map.put(235, "NtWaitForMultipleObjectsEx");
        map.put(236, "NtWriteFile");
        map.put(237, "NtWriteFileGather");
        map.put(238, "NtYieldExecution");
        map.put(239, "ObCreateObject");
        map.put(240, "ObDirectoryObjectType");
        map.put(241, "ObInsertObject");
        map.put(242, "ObMakeTemporaryObject");
        map.put(243, "ObOpenObjectByName");
        map.put(244, "ObOpenObjectByPointer");
        map.put(245, "ObpObjectHandleTable");
        map.put(246, "ObReferenceObjectByHandle");
        map.put(247, "ObReferenceObjectByName");
        map.put(248, "ObReferenceObjectByPointer");
        map.put(249, "ObSymbolicLinkObjectType");
        map.put(250, "ObfDereferenceObject");
        map.put(251, "ObfReferenceObject");
        map.put(252, "PhyGetLinkState");
        map.put(253, "PhyInitialize");
        map.put(254, "PsCreateSystemThread");
        map.put(255, "PsCreateSystemThreadEx");
        map.put(256, "PsQueryStatistics");
        map.put(257, "PsSetCreateThreadNotifyRoutine");
        map.put(258, "PsTerminateSystemThread");
        map.put(259, "PsThreadObjectType");
        map.put(260, "RtlAnsiStringToUnicodeString");
        map.put(261, "RtlAppendStringToString");
        map.put(262, "RtlAppendUnicodeStringToString");
        map.put(263, "RtlAppendUnicodeToString");
        map.put(264, "RtlAssert");
        map.put(265, "RtlCaptureContext");
        map.put(266, "RtlCaptureStackBackTrace");
        map.put(267, "RtlCharToInteger");
        map.put(268, "RtlCompareMemory");
        map.put(269, "RtlCompareMemoryUlong");
        map.put(270, "RtlCompareString");
        map.put(271, "RtlCompareUnicodeString");
        map.put(272, "RtlCopyString");
        map.put(273, "RtlCopyUnicodeString");
        map.put(274, "RtlCreateUnicodeString");
        map.put(275, "RtlDowncaseUnicodeChar");
        map.put(276, "RtlDowncaseUnicodeString");
        map.put(277, "RtlEnterCriticalSection");
        map.put(278, "RtlEnterCriticalSectionAndRegion");
        map.put(279, "RtlEqualString");
        map.put(280, "RtlEqualUnicodeString");
        map.put(281, "RtlExtendedIntegerMultiply");
        map.put(282, "RtlExtendedLargeIntegerDivide");
        map.put(283, "RtlExtendedMagicDivide");
        map.put(284, "RtlFillMemory");
        map.put(285, "RtlFillMemoryUlong");
        map.put(286, "RtlFreeAnsiString");
        map.put(287, "RtlFreeUnicodeString");
        map.put(288, "RtlGetCallersAddress");
        map.put(289, "RtlInitAnsiString");
        map.put(290, "RtlInitUnicodeString");
        map.put(291, "RtlInitializeCriticalSection");
        map.put(292, "RtlIntegerToChar");
        map.put(293, "RtlIntegerToUnicodeString");
        map.put(294, "RtlLeaveCriticalSection");
        map.put(295, "RtlLeaveCriticalSectionAndRegion");
        map.put(296, "RtlLowerChar");
        map.put(297, "RtlMapGenericMask");
        map.put(298, "RtlMoveMemory");
        map.put(299, "RtlMultiByteToUnicodeN");
        map.put(300, "RtlMultiByteToUnicodeSize");
        map.put(301, "RtlNtStatusToDosError");
        map.put(302, "RtlRaiseException");
        map.put(303, "RtlRaiseStatus");
        map.put(304, "RtlTimeFieldsToTime");
        map.put(305, "RtlTimeToTimeFields");
        map.put(306, "RtlTryEnterCriticalSection");
        map.put(307, "RtlUlongByteSwap");
        map.put(308, "RtlUnicodeStringToAnsiString");
        map.put(309, "RtlUnicodeStringToInteger");
        map.put(310, "RtlUnicodeToMultiByteN");
        map.put(311, "RtlUnicodeToMultiByteSize");
        map.put(312, "RtlUnwind");
        map.put(313, "RtlUpcaseUnicodeChar");
        map.put(314, "RtlUpcaseUnicodeString");
        map.put(315, "RtlUpcaseUnicodeToMultiByteN");
        map.put(316, "RtlUpperChar");
        map.put(317, "RtlUpperString");
        map.put(318, "RtlUshortByteSwap");
        map.put(319, "RtlWalkFrameChain");
        map.put(320, "RtlZeroMemory");
        map.put(321, "XboxEEPROMKey");
        map.put(322, "XboxHardwareInfo");
        map.put(323, "XboxHDKey");
        map.put(324, "XboxKrnlVersion");
        map.put(325, "XboxSignatureKey");
        map.put(326, "XeImageFileName");
        map.put(327, "XeLoadSection");
        map.put(328, "XeUnloadSection");
        map.put(329, "READ_PORT_BUFFER_UCHAR");
        map.put(330, "READ_PORT_BUFFER_USHORT");
        map.put(331, "READ_PORT_BUFFER_ULONG");
        map.put(332, "WRITE_PORT_BUFFER_UCHAR");
        map.put(333, "WRITE_PORT_BUFFER_USHORT");
        map.put(334, "WRITE_PORT_BUFFER_ULONG");
        map.put(335, "XcSHAInit");
        map.put(336, "XcSHAUpdate");
        map.put(337, "XcSHAFinal");
        map.put(338, "XcRC4Key");
        map.put(339, "XcRC4Crypt");
        map.put(340, "XcHMAC");
        map.put(341, "XcPKEncPublic");
        map.put(342, "XcPKDecPrivate");
        map.put(343, "XcPKGetKeyLen");
        map.put(344, "XcVerifyPKCS1Signature");
        map.put(345, "XcModExp");
        map.put(346, "XcDESKeyParity");
        map.put(347, "XcKeyTable");
        map.put(348, "XcBlockCrypt");
        map.put(349, "XcBlockCryptCBC");
        map.put(350, "XcCryptService");
        map.put(351, "XcUpdateCrypto");
        map.put(352, "RtlRip");
        map.put(353, "XboxLANKey");
        map.put(354, "XboxAlternateSignatureKeys");
        map.put(355, "XePublicKeyData");
        map.put(356, "HalBootSMCVideoMode");
        map.put(357, "IdexChannelObject");
        map.put(358, "HalIsResetOrShutdownPending");
        map.put(359, "IoMarkIrpMustComplete");
        map.put(360, "HalInitiateShutdown");
        map.put(361, "RtlSnprintf");
        map.put(362, "RtlSprintf");
        map.put(363, "RtlVsnprintf");
        map.put(364, "RtlVsprintf");
        map.put(365, "HalEnableSecureTrayEject");
        map.put(366, "HalWriteSMCScratchRegister");
        map.put(374, "MmDbgAllocateMemory");
        map.put(375, "MmDbgFreeMemory");
        map.put(376, "MmDbgQueryAvailablePages");
        map.put(377, "MmDbgReleaseAddress");
        map.put(378, "MmDbgWriteCheck");
        return map;
    }

    @Override
    public void run() throws Exception {
        Map<Integer, String> names = ordinalNames();
        ReferenceManager rm = currentProgram.getReferenceManager();
        println("== Kernel Image Thunk Table @ " + toAddr(KTHUNK_VA) + " ==");

        int count = 0;
        int resolved = 0;
        int unknownOrdinal = 0;
        int notOrdinalTagged = 0;

        for (int i = 0; i < MAX_ENTRIES; i++) {
            Address slot = toAddr(KTHUNK_VA + (long) i * 4);
            long value = getInt(slot) & 0xFFFFFFFFL;
            if (value == 0) {
                println("-- terminator (0) at index " + i + ", " + i + " real entries --");
                break;
            }
            count++;
            String label;
            if ((value & 0x80000000L) != 0) {
                int ordinal = (int) (value & 0x7FFFFFFFL);
                String name = names.get(ordinal);
                if (name == null) {
                    name = "UNKNOWN_ORDINAL_" + ordinal;
                    unknownOrdinal++;
                } else {
                    resolved++;
                }
                label = name;
            } else {
                notOrdinalTagged++;
                label = String.format("NOT_ORDINAL_TAGGED_0x%x", value);
            }

            try {
                createLabel(slot, label, true, SourceType.USER_DEFINED);
            }
            catch (Exception e) {
                println("  (could not label " + slot + " as " + label + ": " + e.getMessage() + ")");
            }
            setEOLComment(slot, label);

            // who in .text actually calls through this slot?
            List<Reference> refs = new ArrayList<>();
            ReferenceIterator rit = rm.getReferencesTo(slot);
            while (rit.hasNext()) {
                refs.add(rit.next());
            }
            StringBuilder callers = new StringBuilder();
            int shown = 0;
            for (Reference ref : refs) {
                Function f = getFunctionContaining(ref.getFromAddress());
                String callerName = f != null ? f.getName() + "@" + f.getEntryPoint() : ref.getFromAddress().toString();
                if (shown > 0) callers.append(", ");
                callers.append(callerName);
                shown++;
                if (shown >= 5) {
                    callers.append(", ...");
                    break;
                }
            }
            println(String.format("  [%3d] %-18s %-32s xrefs=%d  callers: %s", i, slot, label,
                    refs.size(), callers.toString()));
        }

        println("== summary ==");
        println("real entries: " + count);
        println("resolved to known xboxkrnl names: " + resolved);
        println("unknown ordinal numbers: " + unknownOrdinal);
        println("non-ordinal-tagged slots (unexpected): " + notOrdinalTagged);
    }
}
